'use client'

import jsPDF from 'jspdf'
import html2canvas from 'html2canvas'
import type { PDFGenerationOptions, PDFGenerationResult } from '../types'

export async function captureElement(elementId: string): Promise<HTMLCanvasElement> {
  const element = document.getElementById(elementId)
  if (!element) {
    throw new Error(`Element #${elementId} not found`)
  }

  const html2canvasOpts: Record<string, unknown> = {
    scale: 2,
    useCORS: true,
    allowTaint: true,
    backgroundColor: '#ffffff',
    logging: false,
  }
  const canvas = await html2canvas(element, html2canvasOpts as Html2Canvas.Html2CanvasOptions)

  return canvas
}

export function addPageToPDF(
  pdf: jsPDF,
  canvas: HTMLCanvasElement,
  title: string,
  isFirstPage: boolean
): void {
  const pageWidth = pdf.internal.pageSize.getWidth()
  const pageHeight = pdf.internal.pageSize.getHeight()

  const top = 20
  const bottom = 20
  const left = 15
  const right = 15

  const contentWidth = pageWidth - left - right

  if (!isFirstPage) {
    pdf.addPage()
  }

  pdf.setFontSize(14)
  pdf.setTextColor(30, 58, 95)
  pdf.text(title, left, 15)

  const imgData = canvas.toDataURL('image/png')

  const imgWidth = contentWidth
  const imgHeight = (canvas.height * imgWidth) / canvas.width

  if (imgHeight < pageHeight - top - bottom) {
    pdf.addImage(imgData, 'PNG', left, top, imgWidth, imgHeight)
  } else {
    const scaledHeight = pageHeight - top - bottom
    const scaledWidth = (canvas.width * scaledHeight) / canvas.height
    const xOffset = left + (contentWidth - scaledWidth) / 2
    pdf.addImage(imgData, 'PNG', xOffset, top, scaledWidth, scaledHeight)
    // TODO: implement true multi-page slicing
  }
}

export async function generatePDF(options: PDFGenerationOptions): Promise<PDFGenerationResult> {
  try {
    const pdf = new jsPDF({
      orientation: 'portrait',
      unit: 'mm',
      format: 'a4',
    })

    const pageWidth = pdf.internal.pageSize.getWidth()

    pdf.setFillColor(30, 58, 95)
    pdf.rect(0, 0, pageWidth, 60, 'F')

    pdf.setTextColor(255, 255, 255)
    pdf.setFontSize(28)
    pdf.setFont('helvetica', 'bold')
    pdf.text('StatLab', pageWidth / 2, 28, { align: 'center' })

    pdf.setFontSize(12)
    pdf.setFont('helvetica', 'normal')
    pdf.text('Statistical Analysis Report', pageWidth / 2, 40, { align: 'center' })

    pdf.setTextColor(30, 58, 95)
    pdf.setFontSize(16)
    pdf.setFont('helvetica', 'bold')
    pdf.text(options.title, pageWidth / 2, 85, { align: 'center' })

    if (options.includeTimestamp) {
      pdf.setFontSize(10)
      pdf.setFont('helvetica', 'normal')
      pdf.setTextColor(100, 100, 100)
      const timestamp = new Date().toLocaleDateString('en-GB', {
        day: 'numeric',
        month: 'long',
        year: 'numeric',
        hour: '2-digit',
        minute: '2-digit',
      })
      pdf.text(`Generated: ${timestamp}`, pageWidth / 2, 100, { align: 'center' })
    }

    pdf.setDrawColor(46, 134, 171)
    pdf.setLineWidth(0.5)
    pdf.line(15, 270, pageWidth - 15, 270)
    pdf.setFontSize(9)
    pdf.setTextColor(150, 150, 150)
    pdf.text(
      'Generated by StatLab — Intelligent Statistical Analysis',
      pageWidth / 2,
      278,
      { align: 'center' }
    )

    for (let i = 0; i < options.sections.length; i++) {
      const section = options.sections[i]
      const canvas = await captureElement(section.elementId)
      addPageToPDF(pdf, canvas, section.title, false)
    }

    const totalPages = pdf.getNumberOfPages()
    for (let i = 2; i <= totalPages; i++) {
      pdf.setPage(i)
      pdf.setFontSize(9)
      pdf.setTextColor(150, 150, 150)
      pdf.text(
        `Page ${i - 1} of ${totalPages - 1}`,
        pdf.internal.pageSize.getWidth() / 2,
        pdf.internal.pageSize.getHeight() - 8,
        { align: 'center' }
      )
    }

    pdf.save(options.fileName)
    return { success: true, fileName: options.fileName }
  } catch (error) {
    return { success: false, error: (error as Error).message }
  }
}

export default generatePDF

export type { PDFSection, PDFGenerationOptions, PDFGenerationResult } from '../types'
